I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 435, in script
    show tiger with fade
Exception: Image 'tiger' not found.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 435, in script
    show tiger with fade
  File "/Users/mbrickn/Desktop/renpy-6.99.14-sdk/renpy/ast.py", line 1110, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/mbrickn/Desktop/renpy-6.99.14-sdk/renpy/ast.py", line 1082, in show_imspec
    atl=atl)
  File "/Users/mbrickn/Desktop/renpy-6.99.14-sdk/renpy/exports.py", line 656, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Users/mbrickn/Desktop/renpy-6.99.14-sdk/renpy/display/image.py", line 303, in find_target
    error("Image '%s' not found." % ' '.join(self.name))
  File "/Users/mbrickn/Desktop/renpy-6.99.14-sdk/renpy/display/image.py", line 289, in error
    raise Exception(msg)
Exception: Image 'tiger' not found.

Darwin-16.5.0-x86_64-i386-64bit
Ren'Py 6.99.14.3135
MechaWahoo 0.2
