I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 223, in script
    T "EVIL!"
Exception: Sayer 'T' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 223, in script
    T "EVIL!"
  File "/home/hackathon/Documents/renpy-6.99.10-sdk/renpy/ast.py", line 584, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/hackathon/Documents/renpy-6.99.10-sdk/renpy/ast.py", line 501, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'T' is not defined.

Linux-4.4.9-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
Ren'Py 6.99.10.1227
MechaWahoo 0.0
